# Generated by Django 4.1.4 on 2023-01-17 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0002_posts_userfollowers_userfeeds_postlikes_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Third', to=settings.AUTH_USER_MODEL),
        ),
    ]
