# Generated by Django 4.1.4 on 2023-01-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0003_alter_posts_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='UserFeeds',
        ),
    ]
