# Generated by Django 4.1.4 on 2023-01-21 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0005_posts_userfeeds_postlikes_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(through='apiInstagram.PostLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
