# Generated by Django 4.1.4 on 2023-01-25 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0005_posts_userfeeds_postlikes_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(through='apiInstagram.PostLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='post_id_id',
            field=models.ForeignKey(default='55', on_delete=django.db.models.deletion.CASCADE, related_name='post_First', to='apiInstagram.posts'),
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
