# Generated by Django 4.1.4 on 2023-01-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0006_remove_posts_total_likes_posts_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='post_id',
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='post_id_id',
            field=models.ForeignKey(default='55', on_delete=django.db.models.deletion.CASCADE, related_name='post_First', to='apiInstagram.posts'),
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
