# Generated by Django 4.1.4 on 2023-01-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiInstagram', '0006_remove_posts_total_likes_remove_userfeeds_post_id_and_more'),
        ('apiInstagram', '0007_remove_userfeeds_post_id_userfeeds_post_id_id_and_more'),
    ]

    operations = [
    ]
